version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env


# Auth service
  auth:       
      build:
        context: ./
        dockerfile: ./apps/auth/Dockerfile
      env_file:
        - .env
      depends_on:
        - rabbitmq
      volumes:
        - .:/usr/src/app # any change to base folder should be reflected
        - /usr/src/app/node_modules
      command: npm run start:dev auth # overrides CMD from dockerfile
  
  # API Getway
  api:
    build:
      context: ./
      dockerfile: ./apps/api/Dockerfile
    ports:
      - '4000:5000'
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - auth
    volumes:
      - .:/usr/src/app # any change to base folder should be reflected
      - /usr/src/app/node_modules
    command: npm run start:dev api


  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - ./db/data:/var/lib/mongo/data
  
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env
    
    