version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    env_file:
      - .env

  #  Mongodb
  mongo:
    image: mongo:5.0
    container_name: mongo
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - server-network
    ports:
      - '27017:27017'
    volumes:
      - ./database/db:/data/db
      - ./database/dev.archive:/Databases/dev.archive
      - ./database/production:/Databases/production
  mongo-express:
    image: mongo-express
    container_name: mexpress
    env_file:
      - .env
    networks:
      - server-network
    links:
      - mongo
    restart: unless-stopped
    ports:
      - '8081:8081'
